[tool.poetry]
name = "django-chat-test"
version = "0.0.0"
description = ""
authors = [ "mf2199", ]

[tool.poetry.dependencies]
python = "^3.8"
channels = "^4.0.0"
channels_redis = "^4.0.0"
crispy-bootstrap4 = "^2022.1"
daphne = "^4.0.0"
django = "^4.1.7"
django-crispy-forms = "^2.0.0"
